name: 'Capistrano deploy'
description: 'Deploy an application using capistrano to the given target'
branding:
  icon: 'arrow-right-circle'
  color: 'black'
inputs:
  mrsk_commands:
    description: 'The Capistrano commands to run'
    required: true
    default: '["deploy"]'
  target:  # string
    description: 'Environment where deploy is to be performed to'
    required: false # if no param is given, default cap target will be selected
  deploy_key:
    description: 'Deployment key used for decryption of SSH RSA private key'
    required: true
  enc_rsa_key_pth:
    description: 'Path to SSH private key encrypted with deploy_key'
    required: false
    default: 'config/deploy_id_rsa_enc'
  enc_rsa_key_val:
    description: 'Value of the SSH private key encrypted with deploy_key'
    required: false
  working-directory:
    description: 'The directory from which to run the deploy command'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'lib/run.js'
